export const PATH = {
  HOME: "/",
  SEARCH: "/search",
  MY_PAGE: "/my",
  SIGN_UP: "/signup",
  PASSWORD: "/password",
  MAIN: "/main",
  UNREGISTAL: "/unregistal",
  PROFILEEDIT: "/ProfileEdit",
  TRANSFER: "/transfer/account",
  TRANSFERAMOUNT: "/transfer/amount",
  TRANSFERPASSWORD: "/transfer/password",
  TRANSFERLOG: "/transfer/log",
  QNAREGISTER: "/qna/register",
  QNAMAIN: "/qna/main",
  QNADETAIL: "/qna/detail/:no",
  //SERVER: "https://api.kookmin-timebank.com",
  SERVER: "https://timebank.cs.kookmin.ac.kr",
};
